k8s deployment file

diff --git a/.github/workflows/k3s-e2e-test.yaml b/.github/workflows/k3s-e2e-test.yaml
--- a/.github/workflows/k3s-e2e-test.yaml
+++ b/.github/workflows/k3s-e2e-test.yaml
@@ -85,27 +85,28 @@ jobs:
       - name: Deploy Microservice
         run: |
           kubectl apply -f deployment/deployment.yaml -n default
-          timeout=60
+          timeout=30
           elapsed=0
           while [[ $elapsed -lt $timeout ]]; do
-            deployment_status=$(kubectl get deployment key-value-service -n default -o jsonpath='{.status.conditions[?(@.type=="Available")].status}')
-            replicas_ready=$(kubectl get deployment key-value-service -n default -o jsonpath='{.status.readyReplicas}')
-            replicas_desired=$(kubectl get deployment key-value-service -n default -o jsonpath='{.spec.replicas}')
-
-            if [[ $deployment_status == "True" ]] && [[ $replicas_ready -eq $replicas_desired ]]; then
+            rollout_status=$(kubectl rollout status deployment/key-value-service -n default)
+            if [[ $rollout_status == *"successfully rolled out"* ]]; then
               echo "Microservice deployment is ready."
               break
+            elif [[ $rollout_status == *"is in progress"* ]]; then
+              echo "Microservice deployment is in progress. Waiting..."
+              sleep 5
+              elapsed=$((elapsed+5))
+            else
+              echo "Microservice deployment encountered an error. Printing debug information..."
+              kubectl describe deployment key-value-service -n default
+              exit 1
             fi
-
-            echo "Microservice deployment is not ready yet. Waiting..."
-            kubectl get deployment key-value-service -n default
-            sleep 5
-            elapsed=$((elapsed+5))
           done
 
           if [[ $elapsed -ge $timeout ]]; then
             echo "Timeout exceeded. Microservice deployment is not ready within the specified time."
             exit 1
           fi
+      
       
       
